Repository Sphinx-Society/kaizen-web-client, pull requests merged in 2020-05, with the labels that each got.

#11 SSKW-10 Code of Conduct
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation, feature

#12 SSKW-9 Contribution Guideline
  CONTRIBUTING.md
Labels: documentation, feature

#13 SSKW-2 Github Templates
  .github/ISSUE_TEMPLATE/kaizen-bug-report---.md
  .github/ISSUE_TEMPLATE/kaizen-feature-request---.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, feature

#17 SSKW-16 Bug in github templates
  .github/ISSUE_TEMPLATE/kaizen-feature-request---.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug

#23 SSKW-22 Add checklist section a title in github templates
  .github/ISSUE_TEMPLATE/kaizen-bug-report---.md
  .github/ISSUE_TEMPLATE/kaizen-feature-request---.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, feature

#36 SSKW-5 Added .eslintrc.json file to use standard code style
  .eslintrc.json
Labels: documentation, feature

#37 SSKW-6 Added babelrc and webpack files to have our initial configuration
  .babelrc.json
  webpack.config.js
Labels: documentation, feature

#40 SSKW-14 Add design system into code
  .gitignore
  package-lock.json
  package.json
  postcss.config.js
  server.js
  src/client/assets/fonts/roboto/100.eot
  src/client/assets/fonts/roboto/100.svg
  src/client/assets/fonts/roboto/100.ttf
  src/client/assets/fonts/roboto/100.woff
  src/client/assets/fonts/roboto/100.woff2
  src/client/assets/fonts/roboto/300.eot
  src/client/assets/fonts/roboto/300.svg
  src/client/assets/fonts/roboto/300.ttf
  src/client/assets/fonts/roboto/300.woff
  src/client/assets/fonts/roboto/300.woff2
  src/client/assets/fonts/roboto/400.eot
  src/client/assets/fonts/roboto/400.svg
  src/client/assets/fonts/roboto/400.ttf
  src/client/assets/fonts/roboto/400.woff
  src/client/assets/fonts/roboto/400.woff2
  src/client/assets/fonts/roboto/700.eot
  src/client/assets/fonts/roboto/700.svg
  src/client/assets/fonts/roboto/700.ttf
  src/client/assets/fonts/roboto/700.woff
  src/client/assets/fonts/roboto/700.woff2
  src/client/index.js
  src/client/pages/NotFound.jsx
  src/client/routes/App.js
  src/client/styles/foundations/colors.scss
  src/client/styles/foundations/font-families/roboto.scss
  src/client/styles/foundations/spacing.scss
  src/client/styles/foundations/spacings.scss
  src/client/styles/foundations/typographies.scss
  src/client/styles/foundations/typography.scss
  src/client/styles/index.scss
  webpack.config.js
  webpack.dev.config.js
  webpack.dll.config.js
Labels: design, feature, infrastructure

#41 SSKW-19 Surface atom
  .eslintrc.json
  .storybook/main.js
  package-lock.json
  package.json
  src/client/components/atoms/Surface/Surface.jsx
  src/client/components/atoms/Surface/Surface.scss
  src/client/index.js
  src/client/stories/atoms/Surface/Surface.story.mdx
  src/client/stories/atoms/Surface/Surface.story.scss
  src/client/styles/foundations/colors.scss
  src/client/styles/foundations/font-families/roboto.scss
  webpack.config.js
  webpack.dev.config.js
Labels: documentation, feature

#43 SSKW-42 Added basic integration Cypress and Storybook
  .storybook/main.js
  cypress.json
  cypress/integration/Surface.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/client/components/atoms/Surface/story/Surface.story.mdx
  src/client/components/atoms/Surface/story/Surface.story.scss
  src/client/styles/foundations/typography.scss
Labels: documentation, feature, infrastructure, test

#44 SSKW-42 Modified Cypress tests to standardize recurring commands
  .eslintrc.json
  cypress.json
  cypress/integration/Surface.spec.js
  cypress/support/commands.js
  package-lock.json
  package.json
  src/client/components/atoms/Surface/story/Surface.story.mdx
Labels: test

#45 SSKW-15 Create button atom
  .babelrc.json
  .storybook/main.js
  cypress/fixtures/example.json
  cypress/integration/atoms/Button.spec.js
  cypress/integration/atoms/Surface.spec.js
  package-lock.json
  package.json
  src/client/components/atoms/Button/Button.jsx
  src/client/components/atoms/Button/Button.scss
  src/client/components/atoms/Button/stories/Button.stories.mdx
  src/client/components/atoms/Button/stories/Button.stories.scss
  src/client/components/atoms/Surface/story/Surface.stories.mdx
  src/client/components/atoms/Surface/story/Surface.stories.scss
  src/client/pages/NotFound.jsx
  src/client/styles/foundations/colors.scss
  webpack.dev.config.js
Labels: documentation, feature, test

#48 SSKW-47 Storybook improvement
  .editorconfig
  .storybook/main.js
  .storybook/manager.js
  package.json
  src/client/components/atoms/Button/Button.jsx
  src/client/components/atoms/Button/Button.scss
  src/client/components/atoms/Button/stories/Button.stories.mdx
  src/client/components/atoms/Button/stories/Button.stories.scss
  src/client/components/atoms/Surface/Surface.jsx
  src/client/components/atoms/Surface/Surface.scss
  src/client/components/atoms/Surface/stories/Surface.stories.mdx
  src/client/components/atoms/Surface/stories/Surface.stories.scss
  src/client/components/atoms/Surface/story/Surface.stories.mdx
  src/client/components/atoms/Surface/story/Surface.stories.scss
  src/client/stories/gettingStarted.stories.mdx
  src/client/stories/tests.stories.mdx
  src/client/styles/foundations/spacing.scss
Labels: documentation, feature

#49 SSKW-46 Jest and Enzyme integration
  .eslintrc.json
  cypress/fixtures/example.json
  cypress/integration/atoms/Button.spec.js
  cypress/integration/atoms/Surface.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/client/__mocks__/fileMock.js
  src/client/__mocks__/styleMock.js
  src/client/components/atoms/Button/tests/Button.test.js
  src/client/components/atoms/Surface/tests/Surface.test.js
Labels: documentation, feature, test

#51 SSKW-50 Module packages in exact mode
  package.json
Labels: bug

#52 SSKW-20 Modified atom component Button to reuse as button in mode icon
  src/client/components/atoms/Button/Button.jsx
  src/client/components/atoms/Button/Button.scss
  src/client/components/atoms/Button/stories/Button.stories.mdx
  src/client/components/atoms/Button/stories/Button.stories.scss
  src/client/components/atoms/Button/tests/Button.test.js
  src/client/pages/NotFound.jsx
  src/client/styles/base.scss
  src/client/styles/foundations/colors.scss
  src/client/styles/foundations/spacing.scss
  src/client/styles/foundations/typography.scss
  src/client/styles/general.scss
  src/client/styles/index.scss
  src/client/styles/mixins.scss
  webpack.dev.config.js
Labels: atom, feature

#56 SSKW-25 Datepicker organism
  package.json
  src/client/__mocks__/assets/fileMock.js
  src/client/__mocks__/components/HookComponentMock.js
  src/client/__mocks__/hooks/useMonthDaysMock.js
  src/client/__mocks__/styles/styleMock.js
  src/client/assets/fonts/roboto/100.eot
  src/client/assets/fonts/roboto/100.svg
  src/client/assets/fonts/roboto/100.ttf
  src/client/assets/fonts/roboto/100.woff
  src/client/assets/fonts/roboto/100.woff2
  src/client/assets/fonts/roboto/300.eot
  src/client/assets/fonts/roboto/300.svg
  src/client/assets/fonts/roboto/300.ttf
  src/client/assets/fonts/roboto/300.woff
  src/client/assets/fonts/roboto/300.woff2
  src/client/assets/fonts/roboto/400.eot
  src/client/assets/fonts/roboto/400.svg
  src/client/assets/fonts/roboto/400.ttf
  src/client/assets/fonts/roboto/400.woff
  src/client/assets/fonts/roboto/400.woff2
  src/client/assets/fonts/roboto/700.eot
  src/client/assets/fonts/roboto/700.svg
  src/client/assets/fonts/roboto/700.ttf
  src/client/assets/fonts/roboto/700.woff
  src/client/assets/fonts/roboto/700.woff2
  src/client/components/atoms/Button/Button.scss
  src/client/components/atoms/DatepickerCarousel/DatepickerCarousel.jsx
  src/client/components/atoms/DatepickerCarousel/DatepickerCarousel.scss
  src/client/components/atoms/DatepickerCarousel/stories/DatepickerCarousel.stories.mdx
  src/client/components/atoms/DatepickerCarousel/tests/DatepickerCarousel.test.js
  src/client/components/atoms/DatepickerDay/DatepickerDay.jsx
  src/client/components/atoms/DatepickerDay/DatepickerDay.scss
  src/client/components/atoms/DatepickerDay/stories/DatepickerDay.stories.mdx
  src/client/components/atoms/DatepickerDay/tests/DatepickerDay.test.js
  src/client/components/atoms/Surface/Surface.jsx
  src/client/components/atoms/Surface/Surface.scss
  src/client/components/molecules/DatepickerMenu/DatepickerMenu.jsx
  src/client/components/molecules/DatepickerMenu/DatepickerMenu.scss
  src/client/components/molecules/DatepickerMenu/stories/DatepickerMenu.stories.mdx
  src/client/components/molecules/DatepickerMenu/tests/DatepickerMenu.test.js
  src/client/components/organisms/Datepicker/Datepicker.jsx
  src/client/components/organisms/Datepicker/Datepicker.scss
  src/client/components/organisms/Datepicker/stories/Datepicker.stories.mdx
  src/client/components/organisms/Datepicker/stories/DatepickerWrapper.jsx
  src/client/components/organisms/Datepicker/tests/Datepicker.test.js
  src/client/hooks/useMonthDays/tests/useMonthDays.test.js
  src/client/hooks/useMonthDays/useMonthDays.js
  src/client/hooks/useOutsideClick/tests/useOutsideClick.test.js
  src/client/hooks/useOutsideClick/useOutsideClick.js
  src/client/styles/base.scss
  src/client/styles/foundations/colors.scss
  src/client/styles/foundations/font-families/roboto.scss
  src/client/styles/foundations/spacing.scss
  src/client/styles/foundations/typography.scss
  src/client/styles/mixins.scss
  src/client/utils/date.js
  src/client/utils/tests/date.test.js
Labels: documentation, organism, test

#58 SSKW - 4 Heroku environment
  cypress.json
  package-lock.json
  package.json
  server.js
  webpack.config.js
Labels: feature, infrastructure

#59 SSKW - 3 Github actions
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  src/client/__mocks__/hooks/useMonthDaysMock.js
  src/client/hooks/useMonthDays/tests/useMonthDays.test.js
  src/client/hooks/useMonthDays/useMonthDays.js
  src/client/pages/NotFound.jsx
  src/client/utils/date.js
Labels: feature, infrastructure

#60 SSKW - 3 Github Actions
  .github/workflows/deploy.yml
Labels: feature, infrastructure

#61 SSKW-3 Github Actions
  .github/workflows/deploy.yml
Labels: feature, infrastructure

#62 SSKW - 3 Github Actions
  .dockerignore
  .github/workflows/deploy.yml
  Dockerfile
Labels: feature, infrastructure

#63 SSKW-53 Added Checkbox to use as atom check square
  src/client/components/atoms/Checkbox/Checkbox.jsx
  src/client/components/atoms/Checkbox/Checkbox.scss
  src/client/components/atoms/Checkbox/stories/Checkbox.stories.mdx
  src/client/components/atoms/Checkbox/test/Checkbox.test.js
  src/client/styles/general.scss
Labels: atom, feature

#64 SSKW-26 Added component Toggle to use as atom
  src/client/components/atoms/Checkbox/Checkbox.scss
  src/client/components/atoms/Toogle/Toggle.jsx
  src/client/components/atoms/Toogle/Toggle.scss
  src/client/components/atoms/Toogle/stories/Toggle.stories.mdx
  src/client/components/atoms/Toogle/test/Toggle.test.js
Labels: atom, feature

#65 SSKW - 21 Text input atom
  src/client/components/atoms/Surface/tests/Surface.test.js
  src/client/components/atoms/TextInput/TextInput.jsx
  src/client/components/atoms/TextInput/TextInput.scss
  src/client/components/atoms/TextInput/stories/TextInput.stories.mdx
  src/client/components/atoms/TextInput/tests/TextInput.test.js
  src/client/components/molecules/DatepickerMenu/DatepickerMenu.jsx
  src/client/components/molecules/DatepickerMenu/stories/DatepickerMenu.stories.mdx
  src/client/components/molecules/DatepickerMenu/tests/DatepickerMenu.test.js
  src/client/components/organisms/Datepicker/Datepicker.jsx
  src/client/components/organisms/Datepicker/Datepicker.scss
  src/client/components/organisms/Datepicker/stories/DatepickerWrapper.jsx
  src/client/styles/mixins.scss
Labels: atom, documentation, feature, test

#66 SSKW - 18 Top filter molecule
  src/client/components/molecules/TopFilter/TopFilter.jsx
  src/client/components/molecules/TopFilter/TopFilter.scss
  src/client/components/molecules/TopFilter/stories/TopFilter.stories.mdx
  src/client/components/molecules/TopFilter/tests/TopFilter.test.js
Labels: documentation, feature, molecule, test

#67 SSKW-24 Select atom
  src/client/components/atoms/Select/Select.jsx
  src/client/components/atoms/Select/Select.scss
  src/client/components/atoms/Select/stories/Select.stories.mdx
  src/client/components/atoms/Select/stories/SelectWrapper.jsx
  src/client/components/atoms/Select/test/Select.test.js
  src/client/styles/base.scss
  src/client/styles/foundations/typography.scss
Labels: atom, documentation, feature

#70 SSKW-69 Modified GHaction to display test:coverage
  .github/workflows/ci.yml
Labels: hotfix

#68 SSKW-33 Added files to structure 'Navbar'
  src/client/components/atoms/Select/Select.scss
  src/client/components/organisms/Navbar/Navbar.jsx
  src/client/components/organisms/Navbar/Navbar.scss
  src/client/components/organisms/Navbar/stories/Navbar.stories.mdx
  src/client/components/organisms/Navbar/stories/Navbar.stories.scss
  src/client/components/organisms/Navbar/test/Navbar.test.js
  src/client/styles/general.scss
Labels: documentation, feature, organism, test

#72 SSKW 54 - Table organism
  .storybook/main.js
  package-lock.json
  package.json
  src/client/components/atoms/Logo/Logo.jsx
  src/client/components/atoms/Logo/Logo.scss
  src/client/components/atoms/Logo/stories/Logo.stories.mdx
  src/client/components/atoms/Select/Select.scss
  src/client/components/atoms/Surface/Surface.jsx
  src/client/components/atoms/Surface/Surface.scss
  src/client/components/atoms/TableCell/TableCell.jsx
  src/client/components/atoms/TableCell/TableCell.scss
  src/client/components/atoms/TableCell/stories/TableCell.stories.mdx
  src/client/components/atoms/TextInput/TextInput.jsx
  src/client/components/atoms/TextInput/TextInput.scss
  src/client/components/atoms/TextInput/stories/TextInput.stories.mdx
  src/client/components/molecules/TableBody/TableBody.jsx
  src/client/components/molecules/TableBody/TableBody.scss
  src/client/components/molecules/TableHead/TableHead.jsx
  src/client/components/molecules/TableMenu/TableMenu.jsx
  src/client/components/molecules/TableMenu/TableMenu.scss
  src/client/components/molecules/TablePagination/TablePagination.jsx
  src/client/components/molecules/TablePagination/TablePagination.scss
  src/client/components/molecules/TopFilter/TopFilter.jsx
  src/client/components/organisms/Datepicker/Datepicker.scss
  src/client/components/organisms/Table/Table.jsx
  src/client/components/organisms/Table/Table.scss
  src/client/components/organisms/Table/stories/Table.stories.mdx
  src/client/components/organisms/Table/stories/Table.stories.scss
  src/client/components/organisms/Table/stories/TableWrapper.jsx
  src/client/hooks/useWindowDimensions/useWindowDimensions.js
  src/client/schemas/TableColumn/TableColumn.js
  src/client/schemas/TableColumn/stories/TableColumn.stories.mdx
  src/client/schemas/TableRow/TableRow.js
  src/client/schemas/TableRow/stories/TableRow.stories.mdx
  src/client/schemas/references.js
  src/client/styles/foundations/breakpoints.scss
  src/client/styles/index.scss
  src/client/styles/mixins.scss
Labels: documentation, feature, organism

#75 SSKW-57 Update readme to show more about the project
  README.md
Labels: documentation

#77 SSKW-76 Readable Field atom
  src/client/components/atoms/ReadableField/ReadableField.jsx
  src/client/components/atoms/ReadableField/ReadableField.scss
  src/client/components/atoms/ReadableField/stories/ReadableField.stories.mdx
  src/client/components/atoms/ReadableField/test/ReadableField.test.js
Labels: atom, documentation, feature, test

#71 SSKW-27 Login page
  package-lock.json
  package.json
  src/client/__mocks__/redux/ProviderMock.js
  src/client/assets/images/Logo.png
  src/client/assets/images/Vector1.png
  src/client/assets/images/Vector2.png
  src/client/assets/images/doctor-vector.png
  src/client/assets/images/fondo.png
  src/client/assets/images/fondo2.png
  src/client/components/atoms/ErrorInput/ErrorForm.jsx
  src/client/components/atoms/ErrorInput/ErrorInput.scss
  src/client/components/atoms/TextInput/TextInput.jsx
  src/client/components/organisms/Login-form/LoginForm.jsx
  src/client/components/organisms/Login-form/LoginForm.scss
  src/client/components/organisms/Login-form/stories/LoginForm.stories.mdx
  src/client/components/organisms/Login-form/stories/LoginForm.stories.scss
  src/client/components/organisms/Login-form/tests/LoginForm.test.js
  src/client/components/organisms/ShapesContainer/ShapesContainer.jsx
  src/client/components/organisms/ShapesContainer/ShapesContainer.scss
  src/client/components/organisms/ShapesContainer/stories/ShapesContainer.stories.mdx
  src/client/components/organisms/ShapesContainer/stories/ShapesContainer.stories.scss
  src/client/components/organisms/ShapesContainer/tests/ShapesContainer.test.js
  src/client/components/pages/Login/Login.jsx
  src/client/components/pages/Login/Login.scss
  src/client/components/pages/Login/stories/Login.stories.mdx
  src/client/components/pages/Login/stories/Login.stories.scss
  src/client/components/pages/NotFound.jsx
  src/client/components/templates/LoginTemplate/LoginTemplate.js
  src/client/components/templates/LoginTemplate/LoginTemplate.scss
  src/client/components/templates/LoginTemplate/stories/LoginTemplate.stories.mdx
  src/client/components/templates/LoginTemplate/stories/LoginTemplate.stories.scss
  src/client/hooks/useLoginForm/useLoginForm.js
  src/client/index.js
  src/client/reducers/index.js
  src/client/redux/actions/loginActions.js
  src/client/redux/reducers/LoginReducers/loginReducers.js
  src/client/redux/reducers/LoginReducers/loginReducers.test.js
  src/client/redux/reducers/index.js
  src/client/redux/store/ProviderWrapper.js
  src/client/redux/store/initialState.js
  src/client/redux/store/store.js
  src/client/redux/types/loginTypes.js
  src/client/routes/App.js
  src/client/styles/base.scss
  src/client/styles/foundations/spacing.scss
  src/client/utils/tests/testFuntions.js
  webpack.config.js
  webpack.dev.config.js
Labels: documentation, feature, page, template, test

#83 SSKW-82 Storybook CI deployment fix
  .github/workflows/deploy.yml
Labels: bug, infrastructure

#84 SSKW-82 Storybook CI deployment fix
  package-lock.json
  package.json
Labels: bug, infrastructure

#85 SSKW-82 Storybook CI deployment fix
  .github/workflows/deploy.yml
Labels: bug, infrastructure

#86 SSKW-82 Storybook CI deployment fix
  .github/workflows/deploy.yml
  package.json
Labels: bug, infrastructure

#80 SSKW-73 UserCard organism
  package-lock.json
  package.json
  src/client/components/organisms/UserCard/UserCard.jsx
  src/client/components/organisms/UserCard/UserCard.scss
  src/client/components/organisms/UserCard/stories/UserCard.stories.mdx
  src/client/components/organisms/UserCard/test/UserCard.test.js
  src/client/styles/general.scss
Labels: documentation, feature, organism, test, working on

#87 SSKW-82 Storybook CI deployment fix
  package.json
Labels: bug, infrastructure

#88 SSKW-82 Storybook CI deployment fix
  .github/workflows/deploy.yml
Labels: bug, infrastructure

#89 SSKW-82 Storybook CI deployment fix
  .github/workflows/deploy.yml
  package.json
Labels: bug, infrastructure

#94 SSKW - 92 Main View Provider
  src/client/components/providers/MainViewProvider/MainViewProvider.jsx
  src/client/components/providers/MainViewProvider/MainViewProvider.scss
  src/client/components/providers/MainViewProvider/stories/MainViewProvider.stories.mdx
  src/client/components/providers/MainViewProvider/tests/MainViewProvider.test.js
Labels: documentation, feature, test

#95 SSKW - 31 Exams CRUD page
  package-lock.json
  src/client/components/atoms/Button/Button.scss
  src/client/components/atoms/ReadableField/ReadableField.jsx
  src/client/components/atoms/Surface/Surface.scss
  src/client/components/molecules/TableMenu/TableMenu.scss
  src/client/components/molecules/TablePagination/TablePagination.scss
  src/client/components/organisms/ExamCard/ExamCard.jsx
  src/client/components/organisms/ExamCard/ExamCard.scss
  src/client/components/organisms/ExamCard/stories/ExamCard.stories.mdx
  src/client/components/organisms/ExamCard/tests/ExamCard.test.js
  src/client/components/organisms/Table/Table.jsx
  src/client/components/organisms/Table/Table.scss
  src/client/components/pages/ExamsManagement/ExamsManagement.jsx
  src/client/redux/exams/exams.actions.js
  src/client/redux/exams/exams.reducer.js
  src/client/redux/reducer.js
  src/client/routes/App.js
  webpack.dev.config.js
Labels: documentation, feature, page, test

#91 SSKW-28 Users Management (page)
  src/client/__mocks__/components/UserTableMock.js
  src/client/components/atoms/Checkbox/tests/Checkbox.test.js
  src/client/components/atoms/ReadableField/tests/ReadableField.test.js
  src/client/components/atoms/Select/tests/Select.test.js
  src/client/components/atoms/Toogle/tests/Toggle.test.js
  src/client/components/molecules/ListReadableFields/ListReadableFields.scss
  src/client/components/molecules/ListReadableFields/tests/ListReadableFields.test.js
  src/client/components/organisms/Navbar/tests/Navbar.test.js
  src/client/components/organisms/UserCard/UserCard.jsx
  src/client/components/organisms/UserCard/UserCard.scss
  src/client/components/organisms/UserCard/tests/UserCard.test.js
  src/client/components/pages/UsersManagement/UsersManagement.jsx
  src/client/components/providers/MainViewProvider/MainViewProvider.scss
  src/client/components/templates/UsersManagementTemplate/UsersManagementTemplate.jsx
  src/client/components/templates/UsersManagementTemplate/UsersManagementTemplate.scss
  src/client/components/templates/UsersManagementTemplate/stories/UsersManagementTemplate.stories.mdx
  src/client/components/templates/UsersManagementTemplate/tests/UsersManagementTemplate.test.js
  src/client/routes/App.js
  src/client/schemas/UsersTable/UsersTable.js
  src/client/schemas/UsersTable/stories/UsersTable.stories.mdx
  src/client/schemas/references.js
  src/client/styles/general.scss
Labels: documentation, feature, page, template, test

#98 SSKW - 32 Exam creation page
  package-lock.json
  package.json
  public/index.html
  src/client/components/atoms/Button/Button.jsx
  src/client/components/atoms/Button/Button.scss
  src/client/components/atoms/Button/tests/Button.test.js
  src/client/components/atoms/Checkbox/Checkbox.jsx
  src/client/components/atoms/Checkbox/tests/Checkbox.test.js
  src/client/components/atoms/Select/Select.jsx
  src/client/components/atoms/Select/Select.scss
  src/client/components/atoms/Select/stories/SelectWrapper.jsx
  src/client/components/atoms/Select/tests/Select.test.js
  src/client/components/atoms/TextInput/TextInput.jsx
  src/client/components/atoms/TextInput/TextInput.scss
  src/client/components/molecules/TablePagination/TablePagination.scss
  src/client/components/organisms/ExamCard/stories/ExamCard.stories.mdx
  src/client/components/organisms/Navbar/Navbar.jsx
  src/client/components/organisms/Navbar/Navbar.scss
  src/client/components/organisms/Navbar/tests/Navbar.test.js
  src/client/components/organisms/Table/Table.scss
  src/client/components/organisms/TemplateCard/TemplateCard.jsx
  src/client/components/organisms/TemplateCard/TemplateCard.scss
  src/client/components/organisms/TemplateCard/stories/TemplateCard.stories.mdx
  src/client/components/organisms/TemplateCard/tests/TemplateCard.test.js
  src/client/components/organisms/TemplateFieldCard/TemplateFieldCard.jsx
  src/client/components/organisms/TemplateFieldCard/TemplateFieldCard.scss
  src/client/components/organisms/TemplateForm/TemplateForm.jsx
  src/client/components/organisms/TemplateForm/TemplateForm.scss
  src/client/components/pages/ExamsManagement/ExamsManagement.jsx
  src/client/components/pages/TemplateEditor/TemplateEditor.jsx
  src/client/components/pages/TemplatesManagement/TemplatesManagement.jsx
  src/client/components/providers/MainViewProvider/MainViewProvider.scss
  src/client/components/providers/NavbarProvider/NavbarProvider.jsx
  src/client/components/providers/NavbarProvider/NavbarProvider.scss
  src/client/components/providers/NavbarProvider/tests/NavbarProvider.test.js
  src/client/components/providers/PortalProvider/PortalProvider.jsx
  src/client/components/templates/NavbarProvider/NavbarProvider.scss
  src/client/components/templates/UsersManagementTemplate/UsersManagementTemplate.jsx
  src/client/hooks/useForm/useForm.js
  src/client/redux/exams/exams.actions.js
  src/client/redux/exams/exams.reducer.js
  src/client/redux/reducer.js
  src/client/redux/templates/templates.actions.js
  src/client/redux/templates/templates.actions.requests.js
  src/client/redux/templates/templates.reducer.js
  src/client/routes/App.js
  src/client/routes/paths.js
  src/client/routes/routes.js
  src/client/services/Request.js
  src/client/services/Template.js
  src/client/styles/base.scss
  src/client/styles/foundations/spacing.scss
  src/client/styles/general.scss
  webpack.config.js
  webpack.dev.config.js
Labels: documentation, page, template, test

#100 SSKW - 97 Feedback Provider
  src/client/components/atoms/Alert/Alert.jsx
  src/client/components/atoms/Alert/Alert.scss
  src/client/components/atoms/Button/Button.scss
  src/client/components/pages/Login/Login.jsx
  src/client/components/pages/TemplateEditor/TemplateEditor.jsx
  src/client/components/pages/TemplatesManagement/TemplatesManagement.jsx
  src/client/components/pages/UsersManagement/UsersManagement.jsx
  src/client/components/providers/FeedbackProvider/FeedbackProvider.jsx
  src/client/hooks/useOutsideClick/useOutsideClick.js
  src/client/redux/templates/templates.actions.requests.js
  src/client/styles/base.scss
  src/client/styles/foundations/animations.scss
  src/client/styles/foundations/colors.scss
  src/client/styles/foundations/zIndexes.scss
  src/client/styles/index.scss
Labels: Provider, atom, feature, page

#102 SSKW-30 Settings Page
  src/client/components/organisms/Navbar/Navbar.jsx
  src/client/components/pages/Settings/Settings.jsx
  src/client/components/pages/Settings/Settings.scss
  src/client/components/pages/Settings/test/Settings.test.js
  src/client/routes/paths.js
  src/client/routes/routes.js
Labels: page, test

#103 SSKW-99 Modal Provider and modal dialog
  src/client/components/atoms/Button/Button.scss
  src/client/components/organisms/Modal/Modal.jsx
  src/client/components/organisms/Modal/Modal.scss
  src/client/components/organisms/Modal/stories/Modal.stories.mdx
  src/client/components/organisms/Modal/tests/Modal.test.js
  src/client/components/pages/TemplateEditor/TemplateEditor.jsx
  src/client/components/pages/TemplatesManagement/TemplatesManagement.jsx
  src/client/components/pages/UsersManagement/UsersManagement.jsx
  src/client/components/providers/ModalProvider/ModalProvider.jsx
  src/client/components/providers/ModalProvider/ModalProvider.scss
  src/client/redux/modalDialog/modalDialog.actions.js
  src/client/redux/modalDialog/modalDialog.reducer.js
  src/client/redux/reducer.js
  src/client/styles/foundations/colors.scss
Labels: Provider, documentation, feature, organism, test

#105 SSKW - 104 Integrate templates and user management list
  src/client/__mocks__/redux/ProviderMock.js
  src/client/components/atoms/TableCell/TableCell.jsx
  src/client/components/molecules/TableMenu/TableMenu.jsx
  src/client/components/molecules/TableMenu/TableMenu.scss
  src/client/components/molecules/TablePagination/TablePagination.jsx
  src/client/components/molecules/TablePagination/TablePagination.scss
  src/client/components/organisms/ExamCard/ExamCard.jsx
  src/client/components/organisms/LoginForm/LoginForm.scss
  src/client/components/organisms/Table/Table.jsx
  src/client/components/organisms/Table/Table.scss
  src/client/components/organisms/TemplateCard/TemplateCard.jsx
  src/client/components/organisms/TemplateFieldCard/TemplateFieldCard.jsx
  src/client/components/organisms/TemplateForm/TemplateForm.jsx
  src/client/components/organisms/TemplateForm/TemplateForm.scss
  src/client/components/organisms/UserCard/UserCard.jsx
  src/client/components/organisms/UserCard/tests/UserCard.test.js
  src/client/components/pages/ExamsHistory/ExamsHistory.jsx
  src/client/components/pages/TemplateEditor/TemplateEditor.jsx
  src/client/components/pages/TemplatesManagement/TemplatesManagement.jsx
  src/client/components/pages/UsersManagement/UsersManagement.jsx
  src/client/components/providers/MainViewProvider/MainViewProvider.jsx
  src/client/components/providers/MainViewProvider/MainViewProvider.scss
  src/client/components/templates/UsersManagementTemplate/UsersManagementTemplate.jsx
  src/client/components/templates/UsersManagementTemplate/UsersManagementTemplate.scss
  src/client/components/templates/UsersManagementTemplate/stories/UsersManagementTemplate.stories.mdx
  src/client/components/templates/UsersManagementTemplate/tests/UsersManagementTemplate.test.js
  src/client/redux/exams/exams.actions.js
  src/client/redux/exams/exams.actions.requests.js
  src/client/redux/exams/exams.reducer.js
  src/client/redux/feedback/feedback.utils.js
  src/client/redux/modalDialog/modalDialog.actions.js
  src/client/redux/reducer.js
  src/client/redux/templates/templates.actions.js
  src/client/redux/templates/templates.actions.requests.js
  src/client/redux/templates/templates.reducer.js
  src/client/redux/user/user.actions.js
  src/client/redux/user/user.actions.requests.js
  src/client/redux/user/user.reducer.js
  src/client/routes/paths.js
  src/client/routes/routes.js
  src/client/services/Exam.js
  src/client/services/Template.js
  src/client/services/User.js
  src/client/utils/error.js
Labels: Provider, feature, page

#107 SSKW-106 Modified UserCard Storybook and more to fix a prop removed
  src/client/components/organisms/UserCard/UserCard.jsx
  src/client/components/organisms/UserCard/stories/UserCard.stories.mdx
  src/client/components/organisms/UserCard/tests/UserCard.test.js
  src/client/components/pages/UsersManagement/UsersManagement.jsx
Labels: bug, documentation, organism, test

#109 SSKW 101 - Patient Home Page
  src/client/components/atoms/Button/Button.scss
  src/client/components/organisms/ExamCard/ExamCard.jsx
  src/client/components/organisms/TestCard/TestCard.jsx
  src/client/components/organisms/TestCard/TestCard.scss
  src/client/components/pages/TestsHistory/TestsHistory.jsx
  src/client/redux/exams/exams.actions.js
  src/client/redux/exams/exams.actions.requests.js
  src/client/redux/exams/exams.reducer.js
  src/client/redux/feedback/feedback.reducer.js
  src/client/redux/reducer.js
  src/client/redux/user/user.actions.js
  src/client/redux/user/user.actions.requests.js
  src/client/redux/user/user.reducer.js
  src/client/routes/paths.js
  src/client/routes/routes.js
  src/client/services/Exam.js
  src/client/services/Template.js
  src/client/services/User.js
Labels: page

#110 SSKW - 108 Integrate login functionality [Front end / backend]
  src/client/components/atoms/TextInput/TextInput.jsx
  src/client/components/organisms/LoginForm/LoginForm.jsx
  src/client/components/organisms/LoginForm/tests/LoginForm.test.js
  src/client/components/pages/Login/Login.jsx
  src/client/components/pages/Login/Login.scss
  src/client/components/pages/Login/stories/Login.stories.mdx
  src/client/components/pages/Login/stories/Login.stories.scss
  src/client/components/templates/LoginTemplate/LoginTemplate.jsx
  src/client/components/templates/LoginTemplate/stories/LoginTemplate.stories.mdx
  src/client/components/templates/LoginTemplate/stories/LoginTemplate.stories.scss
  src/client/redux/user/user.actions.requests.js
  src/client/routes/paths.js
  src/client/services/User.js
Labels: feature

#112 SSKW-111 Add evidence and storybook to the Alert atom
  src/client/components/atoms/Alert/Alert.jsx
  src/client/components/atoms/Alert/Alert.scss
  src/client/components/atoms/Alert/stories/Alert.stories.mdx
  src/client/components/atoms/Alert/tests/Alert.test.js
Labels: atom, documentation, test

#116 SSKW-29 User profile page
  package-lock.json
  package.json
  src/client/__mocks__/redux/ProviderMock.js
  src/client/__mocks__/redux/userPrfoileMock.js
  src/client/components/atoms/DatepickerDay/DatepickerDay.jsx
  src/client/components/atoms/Select/Select.scss
  src/client/components/atoms/UserCover/UserCover.jsx
  src/client/components/atoms/UserCover/UserCover.scss
  src/client/components/hocs/withAuth.jsx
  src/client/components/hocs/withUserData.jsx
  src/client/components/hocs/withoutAuth.jsx
  src/client/components/organisms/Datepicker/Datepicker.jsx
  src/client/components/organisms/Datepicker/Datepicker.scss
  src/client/components/organisms/LoginForm/LoginForm.jsx
  src/client/components/organisms/Navbar/Navbar.jsx
  src/client/components/organisms/Navbar/tests/Navbar.test.js
  src/client/components/organisms/UserCard/UserCard.jsx
  src/client/components/organisms/UserProfile/UserProfile.jsx
  src/client/components/organisms/UserProfile/UserProfile.scss
  src/client/components/organisms/UserProfile/stories/UserProfile.stories.mdx
  src/client/components/organisms/UserProfile/test/UserProfile.test.js
  src/client/components/pages/CreateUser/CreateUser.jsx
  src/client/components/pages/CreateUser/UserProfile.scss
  src/client/components/pages/EditUser/UserProfile.scss
  src/client/components/pages/EditUser/ViewUser.jsx
  src/client/components/pages/Login/Login.jsx
  src/client/components/pages/Main/Main.jsx
  src/client/components/pages/Settings/Settings.jsx
  src/client/components/pages/Settings/test/Settings.test.js
  src/client/components/pages/TemplatesManagement/TemplatesManagement.jsx
  src/client/components/pages/UserProfile/UserProfile.jsx
  src/client/components/pages/UserProfile/UserProfile.scss
  src/client/components/pages/UsersManagement/UsersManagement.jsx
  src/client/components/pages/ViewUser/UserProfile.scss
  src/client/components/pages/ViewUser/ViewUser.jsx
  src/client/components/providers/MainViewProvider/MainViewProvider.jsx
  src/client/components/providers/NavbarProvider/NavbarProvider.jsx
  src/client/components/providers/NavbarProvider/tests/NavbarProvider.test.js
  src/client/hooks/useForm/useForm.js
  src/client/redux/user/user.actions.js
  src/client/redux/user/user.actions.requests.js
  src/client/redux/user/user.reducer.js
  src/client/routes/paths.js
  src/client/routes/routes.js
  src/client/services/Request.js
  src/client/services/User.js
  src/client/styles/general.scss
  src/client/utils/cookie.js
Labels: documentation, feature, organism, page, test

#118 SSKW - 117 Patient Workflow
  jest.init.js
  package-lock.json
  package.json
  src/client/__mocks__/redux/ProviderMock.js
  src/client/components/hocs/withUserData.jsx
  src/client/components/organisms/LoginForm/LoginForm.jsx
  src/client/components/organisms/Navbar/Navbar.jsx
  src/client/components/pages/CreateUser/CreateUser.jsx
  src/client/components/pages/CreateUser/CreateUser.scss
  src/client/components/pages/EditUser/UserProfile.scss
  src/client/components/pages/EditUser/ViewUser.jsx
  src/client/components/pages/Main/Main.jsx
  src/client/components/pages/Settings/Settings.jsx
  src/client/components/pages/Settings/test/Settings.test.js
  src/client/components/pages/TemplatesManagement/TemplatesManagement.jsx
  src/client/components/pages/TestsHistory/TestsHistory.jsx
  src/client/components/pages/UserProfile/UserProfile.jsx
  src/client/components/pages/UserProfile/UserProfile.scss
  src/client/components/pages/ViewUser/UserProfile.scss
  src/client/components/pages/ViewUser/ViewUser.jsx
  src/client/components/providers/MainViewProvider/MainViewProvider.jsx
  src/client/components/providers/MainViewProvider/tests/MainViewProvider.test.js
  src/client/components/providers/ModalProvider/ModalProvider.jsx
  src/client/hooks/useForm/tests/useForm.test.js
  src/client/redux/feedback/feedback.actions.js
  src/client/redux/feedback/feedback.reducer.js
  src/client/redux/feedback/feedback.reducer.test.js
  src/client/redux/feedback/feedback.utils.js
  src/client/redux/modalDialog/modalDialog.reducer.js
  src/client/redux/modalDialog/modalDialog.reducer.test.js
  src/client/redux/templates/templates.actions.js
  src/client/redux/templates/templates.reducer.js
  src/client/redux/templates/templates.reducer.test.js
  src/client/redux/user/user.actions.js
  src/client/redux/user/user.actions.requests.js
  src/client/redux/user/user.reducer.js
  src/client/redux/user/user.reducer.test.js
  src/client/services/Request.js
  src/client/services/Template.js
  src/client/services/User.js
  src/client/services/tests/Request.test.js
  src/client/services/tests/Template.test.js
  src/client/services/tests/User.test.js
  src/client/utils/auth.js
  src/client/utils/error.js
  src/client/utils/tests/auth.test.js
  src/client/utils/tests/cookie.test.js
  src/client/utils/tests/error.test.js
Labels: documentation, feature, page, test

#125 SSKW-124 Env variables not working on heroku
  src/client/services/Request.js
  src/client/services/tests/Request.test.js
Labels: bug

#126 SSKW-124 Env variables not working on heroku
  webpack.config.js
Labels: bug

#130 SSKW-115 Doctor WorkFlow
  src/client/components/organisms/Modal/Modal.jsx
  src/client/components/organisms/Navbar/Navbar.jsx
  src/client/components/organisms/UserCard/UserCard.jsx
  src/client/components/organisms/UserCard/stories/UserCard.stories.mdx
  src/client/components/organisms/UserCard/tests/UserCard.test.js
  src/client/components/organisms/UserProfile/UserProfile.jsx
  src/client/components/organisms/UserProfile/UserProfile.scss
  src/client/components/organisms/UserProfile/stories/UserProfile.stories.mdx
  src/client/components/organisms/UserProfile/test/UserProfile.test.js
  src/client/components/pages/Main/Main.jsx
  src/client/components/pages/PatientTests/PatientTests.jsx
  src/client/components/pages/PatientsManagement/PatientsManagement.jsx
  src/client/components/pages/UserProfile/UserProfile.jsx
  src/client/components/pages/UsersManagement/UsersManagement.jsx
  src/client/components/providers/MainViewProvider/MainViewProvider.jsx
  src/client/components/providers/MainViewProvider/MainViewProvider.scss
  src/client/redux/user/user.actions.js
  src/client/redux/user/user.actions.requests.js
  src/client/redux/user/user.reducer.js
  src/client/routes/paths.js
  src/client/routes/routes.js
  src/client/services/User.js
  src/client/styles/foundations/spacing.scss
Labels: Provider, feature, page

#131 SSKW-129 Change environment management way
  package-lock.json
  package.json
  src/client/services/Request.js
  src/client/services/tests/Request.test.js
  webpack.config.js
  webpack.dev.config.js
Labels: bug

#122 SSKW-120 Integrate massive users
  src/client/components/atoms/Alert/Alert.jsx
  src/client/components/atoms/FileInput/FileInput.jsx
  src/client/components/atoms/FileInput/FileInput.scss
  src/client/components/organisms/Modal/Modal.jsx
  src/client/components/pages/UsersManagement/UsersManagement.jsx
  src/client/components/pages/UsersManagement/UsersManagement.scss
  src/client/components/providers/ModalProvider/ModalProvider.jsx
  src/client/redux/user/user.actions.js
  src/client/redux/user/user.actions.requests.js
  src/client/redux/user/user.reducer.js
  src/client/services/User.js
  src/client/utils/csv.js
Labels: feature

#127 SSKW-121 Integrate notifications in desktop
  server.js
  src/client/components/pages/UsersManagement/UsersManagement.jsx
  src/client/index.js
  src/client/redux/user/user.actions.requests.js
  src/client/utils/serviceWorkers/serviceWorker.js
  src/client/utils/serviceWorkers/sw.js
Labels: feature

#132 SSKW-119 When a template is searched and pagination is used, search is not consistent
  src/client/components/organisms/Table/Table.jsx
  src/client/components/organisms/UserCard/UserCard.scss
  src/client/components/pages/TemplatesManagement/TemplatesManagement.jsx
  src/client/components/pages/UsersManagement/UsersManagement.jsx
  src/client/components/pages/UsersManagement/UsersManagement.scss
  src/client/components/providers/MainViewProvider/MainViewProvider.jsx
  src/client/components/providers/MainViewProvider/MainViewProvider.scss
  src/client/redux/user/user.actions.requests.js
  src/client/services/User.js
  src/client/styles/general.scss
Labels: bug
